---
- hosts: all
  become: true
  tasks:
    - name: Installating the nginx
      ansible.builtin.apt:
        name: nginx
        state: present
    - name: Copying the files
      ansible.builtin.copy:
        src:  /home/patel/hostingonansible/
        dest: /var/www/html
        owner: root
        group: root
        mode: '0777'
